[project]
name = "FitVision"
version = "0.1.0"
description = "A personal app for keeping track of individual trainings"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mediapipe>=0.10.21",
    "opencv-python>=4.11.0.86",
]
